name: Cache Dependencies Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: prime-cache-63b237d
        id: cache-step
        uses: actions/cache@v4
        with:
          path: node_modules   # folder to cache
          key: cache-63b237d

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
